# Generated by Django 5.1.6 on 2025-03-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0002_alter_brands_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='cat_imgs/'),
        ),
    ]
