# Generated by Django 5.1.6 on 2025-03-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0006_alter_category_options_brands_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.RemoveField(
            model_name='brands',
            name='slug',
        ),
    ]
