# Generated by Django 5.1.6 on 2025-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0010_products_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.IntegerField(),
        ),
    ]
