# Generated by Django 5.1.6 on 2025-04-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0002_auto_20250402_1642'),
        ('fypapp', '0015_cart'),
    ]

    operations = [
    ]
