# Generated by Django 5.1.6 on 2025-04-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0016_merge_0002_auto_20250402_1642_0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fypapp.productattribute'),
        ),
    ]
