# Generated by Django 5.1.6 on 2025-04-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0017_wishlistitem_attribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'product', 'attribute')},
        ),
    ]
