# Generated by Django 5.1.6 on 2025-04-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0001_initial'),
    ]

    operations = [
    ]
