# Generated by Django 5.1.6 on 2025-03-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': '2. Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': '3. Products'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name_plural': '4. Ram'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name_plural': '5. Stoarge'},
        ),
        migrations.AddField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
