# Generated by Django 5.1.6 on 2025-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
