# Generated by Django 5.1.6 on 2025-03-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0005_alter_products_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AddField(
            model_name='brands',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
