# Generated by Django 5.1.6 on 2025-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0007_alter_category_options_remove_brands_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(null=True, upload_to='product_imgs/'),
        ),
    ]
