# Generated by Django 5.1.6 on 2025-03-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0008_productattribute_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '6. Products_attribute'},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='image',
        ),
    ]
