# Generated by Django 5.1.6 on 2025-03-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0009_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
