# Generated by Django 5.1.6 on 2025-03-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0013_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
